---
- name: Update prepare
  hosts: sandbox
  gather_facts: no
  vars:
    additional_bridge: true
    bridge_name: int_bridge
  tasks:
    - name: Check if {{ bridge_name }} is active
      shell: nmcli connection show --active |grep int | awk '{print $1}'
      register: nmcli_command_result
      when: additional_bridge == true

    - name: Start internal bridge
      command:
        cmd: nmcli con up int_bridge
      when: 
        - additional_bridge == true  
        - bridge_name not in nmcli_command_result.stdout
    
    - name: Ensure that vms are running
      community.libvirt.virt:
        name: "{{ item }}"
        state: running
      with_inventory_hostnames:
        - infra

- name: Check if systems are up and running
  hosts: all
  gather_facts: no
  tasks:
    - name: Verify if hosts are up and running
      wait_for_connection:
        delay: 5
        timeout: 300

- name: Sync /etc/hosts form sandbox
  hosts: all
  gather_facts: no
  tasks:
    - name: Sync /etc/hosts
      synchronize:
        src: /etc/hosts
        dest: /etc/hosts
      delegate_to: sandbox

- name: Update hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Upgrade all packages to latest version
      dnf:
        name: "*"
        state: latest 
      register: update
  ignore_errors: true

- name: Reboot and shutdown hosts
  hosts: testhosts
  gather_facts: no
  tasks:
    - name: Reboot updated hosts
      reboot:
    
    - name: Wait for host startup after reboot
      wait_for_connection:
        delay: 10
        timeout: 300
          
    - name: Shutdown
      community.general.shutdown:
